[tool.flet.android]
package_name = "com.shrey.godjarvis"
permissions = [
    "INTERNET",
    "RECORD_AUDIO",
    "FOREGROUND_SERVICE",
    "READ_EXTERNAL_STORAGE",
    "WRITE_EXTERNAL_STORAGE",
    "MANAGE_EXTERNAL_STORAGE", # ðŸ”¥ The God Key for Files
    "QUERY_ALL_PACKAGES"
]

[tool.flet.android.manifest]
"android:foregroundServiceType" = "microphone"
"android:requestLegacyExternalStorage" = "true"
