[tool.flet]
product_name = "VEGA AI"
org = "com.shrey.vega"
description = "Ghost AI Assistant"

[tool.flet.android]
package_name = "com.shrey.vega"
build_number = 1
permissions = [
    "INTERNET",
    "RECORD_AUDIO",
    "FOREGROUND_SERVICE",
    "WAKE_LOCK",           # Screen off hone par bhi chalega
    "SYSTEM_ALERT_WINDOW"  # Background se upar aane ke liye
]

[tool.flet.android.manifest]
"android:foregroundServiceType" = "microphone"
"android:usesCleartextTraffic" = "true"
